// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/vo/Address.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Cook: typeof import('./src/components/Cook.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    Email: typeof import('./src/components/vo/Email.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    File: typeof import('./src/components/vo/File.vue')['default']
    FoodStatus: typeof import('./src/components/FoodStatus.vue')['default']
    GetMenu: typeof import('./src/components/GetMenu.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    Kitchen: typeof import('./src/components/Kitchen.vue')['default']
    KitchenGrid: typeof import('./src/components/ui/KitchenGrid.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuGrid: typeof import('./src/components/ui/MenuGrid.vue')['default']
    MenuIds: typeof import('./src/components/MenuIds.vue')['default']
    MenuIdsDetailGrid: typeof import('./src/components/ui/MenuIdsDetailGrid.vue')['default']
    Money: typeof import('./src/components/vo/Money.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    Order: typeof import('./src/components/Order.vue')['default']
    OrderStatus: typeof import('./src/components/OrderStatus.vue')['default']
    Payment: typeof import('./src/components/vo/Payment.vue')['default']
    Photo: typeof import('./src/components/vo/Photo.vue')['default']
    Rating: typeof import('./src/components/vo/Rating.vue')['default']
    RegisterMenu: typeof import('./src/components/RegisterMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sales: typeof import('./src/components/Sales.vue')['default']
    SalesGrid: typeof import('./src/components/ui/SalesGrid.vue')['default']
    Serve: typeof import('./src/components/Serve.vue')['default']
    String: typeof import('./src/components/primitives/String.vue')['default']
    TableOrder: typeof import('./src/components/TableOrder.vue')['default']
    TableOrderGrid: typeof import('./src/components/ui/TableOrderGrid.vue')['default']
    TableOrderId: typeof import('./src/components/TableOrderId.vue')['default']
    TableOrderIdDetailGrid: typeof import('./src/components/ui/TableOrderIdDetailGrid.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    User: typeof import('./src/components/vo/User.vue')['default']
    Weather: typeof import('./src/components/vo/Weather.vue')['default']
  }
}
