---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu
  labels:
    app: menu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu
  template:
    metadata:
      labels:
        app: menu
    spec:
      containers:
        - name: menu
          image: username/menu:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: table
  labels:
    app: table
spec:
  replicas: 1
  selector:
    matchLabels:
      app: table
  template:
    metadata:
      labels:
        app: table
    spec:
      containers:
        - name: table
          image: username/table:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: salesanalysis
  labels:
    app: salesanalysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salesanalysis
  template:
    metadata:
      labels:
        app: salesanalysis
    spec:
      containers:
        - name: salesanalysis
          image: username/salesanalysis:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchen
  labels:
    app: kitchen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchen
  template:
    metadata:
      labels:
        app: kitchen
    spec:
      containers:
        - name: kitchen
          image: username/kitchen:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: menu
  labels:
    app: menu
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: menu


---


apiVersion: v1
kind: Service
metadata:
  name: table
  labels:
    app: table
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: table


---


apiVersion: v1
kind: Service
metadata:
  name: salesanalysis
  labels:
    app: salesanalysis
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: salesanalysis


---


apiVersion: v1
kind: Service
metadata:
  name: kitchen
  labels:
    app: kitchen
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kitchen

